# database 配置文件
# 一般来说，建议使用小写字母。使用小写字母可以增加配置文件的一致性和可读性，并且有助于避免因为大小写不一致而导致的错误。

# 以cityName区分
city1:
  host: ip
  port: 端口
  user: 用户名
  password: 密码
  dbname: 数据库名

city2:
  host: ip
  port: 端口
  user: 用户名
  password: 密码
  dbname: 数据库名