// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSysCustomer = "sys_customer"

// SysCustomer mapped from table <sys_customer>
type SysCustomer struct {
	YHBH                    string     `gorm:"column:YHBH;primaryKey" json:"YHBH"`
	BARCODE                 *string    `gorm:"column:BARCODE" json:"BARCODE"`
	YHDZ                    *string    `gorm:"column:YHDZ" json:"YHDZ"`
	ISUSED                  *string    `gorm:"column:ISUSED;default:0" json:"ISUSED"`
	TCH                     *string    `gorm:"column:TCH" json:"TCH"`
	WSTime                  *time.Time `gorm:"column:WSTime" json:"WSTime"`
	UPDDTTM                 *time.Time `gorm:"column:UPD_DTTM;default:getdate()" json:"UPD_DTTM"`
	ADDDTTM                 *time.Time `gorm:"column:ADD_DTTM;default:getdate()" json:"ADD_DTTM"`
	BJBH                    *string    `gorm:"column:BJBH" json:"BJBH"`
	STATE                   *string    `gorm:"column:STATE" json:"STATE"`
	DTNAME                  *string    `gorm:"column:DTNAME" json:"DTNAME"`
	CMNAME                  *string    `gorm:"column:CMNAME" json:"CMNAME"`
	LXR                     *string    `gorm:"column:LXR" json:"LXR"`
	LXDH                    *string    `gorm:"column:LXDH" json:"LXDH"`
	LXDH2                   *string    `gorm:"column:LXDH2" json:"LXDH2"`
	LXDH3                   *string    `gorm:"column:LXDH3" json:"LXDH3"`
	MARK                    *string    `gorm:"column:MARK" json:"MARK"`
	COMMENTTIME             *time.Time `gorm:"column:COMMENTTIME" json:"COMMENTTIME"`
	COMMENT                 *string    `gorm:"column:COMMENT" json:"COMMENT"`
	LOCKED                  *string    `gorm:"column:LOCKED" json:"LOCKED"`
	LockTime                *time.Time `gorm:"column:LockTime" json:"LockTime"`
	LOCKCustomer            *string    `gorm:"column:LOCKCustomer" json:"LOCKCustomer"`
	OPERATOR                *string    `gorm:"column:OPERATOR" json:"OPERATOR"`
	COMMENTDataRec          *string    `gorm:"column:COMMENT_DataRec" json:"COMMENT_DataRec"`
	QueryBaseData           *float64   `gorm:"column:QueryBaseData" json:"QueryBaseData"`
	QueryData               *float64   `gorm:"column:QueryData" json:"QueryData"`
	QueryTime               *time.Time `gorm:"column:QueryTime;default:getdate()" json:"QueryTime"`
	YHDZYG                  *string    `gorm:"column:YHDZ_YG" json:"YHDZ_YG"`
	IsGasOverflow           *string    `gorm:"column:isGasOverflow" json:"isGasOverflow"`
	IsGasOverflowTime       *time.Time `gorm:"column:isGasOverflowTime" json:"isGasOverflowTime"`
	OpenDesc                *string    `gorm:"column:OpenDesc" json:"OpenDesc"`
	IsWatchMeter            *int64     `gorm:"column:isWatchMeter" json:"isWatchMeter"`
	YFFIsShow               *int64     `gorm:"column:YFF_IsShow" json:"YFF_IsShow"`
	YFFRestMoney            *float64   `gorm:"column:YFF_RestMoney" json:"YFF_RestMoney"`
	YFFRestGas              *float64   `gorm:"column:YFF_RestGas" json:"YFF_RestGas"`
	YFFCISSettleGas         *float64   `gorm:"column:YFF_CISSettleGas" json:"YFF_CISSettleGas"`
	YFFCISSettleTime        *time.Time `gorm:"column:YFF_CISSettleTime" json:"YFF_CISSettleTime"`
	VersionUsed             *string    `gorm:"column:VersionUsed" json:"VersionUsed"`
	VersionFac              *string    `gorm:"column:VersionFac" json:"VersionFac"`
	TaskDes                 *string    `gorm:"column:TaskDes" json:"TaskDes"`
	CheckTime               *time.Time `gorm:"column:CheckTime" json:"CheckTime"`
	OpenAcountTime          *time.Time `gorm:"column:OpenAcountTime;default:getdate()" json:"OpenAcountTime"`
	CISSECTNO               *string    `gorm:"column:CIS_SECT_NO" json:"CIS_SECT_NO"`
	CISSECTNAME             *string    `gorm:"column:CIS_SECT_NAME" json:"CIS_SECT_NAME"`
	LeakGas                 *string    `gorm:"column:LeakGas" json:"LeakGas"`
	LastValve               *string    `gorm:"column:LastValve" json:"LastValve"`
	LastValveTime           *time.Time `gorm:"column:LastValveTime" json:"LastValveTime"`
	IsGasOverflowReason     *string    `gorm:"column:isGasOverflowReason" json:"isGasOverflowReason"`
	IsGasOverflowManage     *string    `gorm:"column:isGasOverflowManage" json:"isGasOverflowManage"`
	IsGasOverflowManageTime *time.Time `gorm:"column:isGasOverflowManageTime" json:"isGasOverflowManageTime"`
	Bankcard                *string    `gorm:"column:bankcard" json:"bankcard"`
	YFFYearSettleMoney      *float64   `gorm:"column:YFF_YearSettleMoney" json:"YFF_YearSettleMoney"`
	ComplaintNum            *int64     `gorm:"column:ComplaintNum" json:"ComplaintNum"`
	ComplaintRecord         *string    `gorm:"column:ComplaintRecord" json:"ComplaintRecord"`
	IsHeating               *string    `gorm:"column:IsHeating" json:"IsHeating"`
	IsHeatingRecord         *string    `gorm:"column:IsHeatingRecord" json:"IsHeatingRecord"`
	IsSendSMS               *string    `gorm:"column:IsSendSMS" json:"IsSendSMS"`
	IsGuShu                 *string    `gorm:"column:IsGuShu" json:"IsGuShu"`
	TchEnableTime           *time.Time `gorm:"column:TchEnableTime" json:"TchEnableTime"`
	TchDisableTime          *time.Time `gorm:"column:TchDisableTime" json:"TchDisableTime"`
	LongSuddenGasOverflow   *string    `gorm:"column:LongSuddenGasOverflow" json:"LongSuddenGasOverflow"`
	CheckWanWei             *string    `gorm:"column:checkWanWei" json:"checkWanWei"`
	PotentialUsers          *int64     `gorm:"column:PotentialUsers" json:"PotentialUsers"`
	ImportComment           *string    `gorm:"column:importComment" json:"importComment"`
	PhoneSupport            *bool      `gorm:"column:PhoneSupport" json:"PhoneSupport"`
	BuName                  *string    `gorm:"column:buName" json:"buName"`
	BukeyBuNum              *string    `gorm:"column:bukeyBuNum" json:"bukeyBuNum"`
	BuLocation              *string    `gorm:"column:buLocation" json:"buLocation"`
	BuOperator              *string    `gorm:"column:buOperator" json:"buOperator"`
	ChLastData              *int64     `gorm:"column:chLastData" json:"chLastData"`
	ChAccData               *int64     `gorm:"column:chAccData" json:"chAccData"`
	ChLastTime              *time.Time `gorm:"column:chLastTime" json:"chLastTime"`
	ChAddTime               *time.Time `gorm:"column:chAddTime;default:getdate()" json:"chAddTime"`
	ChBattery               *int64     `gorm:"column:chBattery" json:"chBattery"`
	Chvalve                 *int64     `gorm:"column:chvalve" json:"chvalve"`
	ChCurrentValve          *int64     `gorm:"column:chCurrentValve" json:"chCurrentValve"`
	ChReadType              *string    `gorm:"column:chReadType" json:"chReadType"`
	ChisDRError             *bool      `gorm:"column:chisDRError;default:0" json:"chisDRError"`
	AlarmLID1               *string    `gorm:"column:AlarmLID1" json:"AlarmLID1"`
	AlarmLID2               *string    `gorm:"column:AlarmLID2" json:"AlarmLID2"`
	Addtime                 *time.Time `gorm:"column:Addtime;default:getdate()" json:"Addtime"`
	Jzq1                    *string    `gorm:"column:jzq1" json:"jzq1"`
	Jzq2                    *string    `gorm:"column:jzq2" json:"jzq2"`
	Cenghao                 *string    `gorm:"column:cenghao" json:"cenghao"`
	HRSmsSendtime           *time.Time `gorm:"column:HRSmsSendtime" json:"HRSmsSendtime"`
	AlarmTime1              *time.Time `gorm:"column:AlarmTime1" json:"AlarmTime1"`
	AlarmTime2              *time.Time `gorm:"column:AlarmTime2" json:"AlarmTime2"`
	Alarmcheck              *string    `gorm:"column:Alarmcheck" json:"Alarmcheck"`
	Alarmchecktime          *time.Time `gorm:"column:Alarmchecktime" json:"Alarmchecktime"`
	AlarmAddtime            *time.Time `gorm:"column:Alarm_addtime" json:"Alarm_addtime"`
	AlarmUploadtime         *time.Time `gorm:"column:Alarm_uploadtime" json:"Alarm_uploadtime"`
	AlarmPoweron            *time.Time `gorm:"column:Alarm_poweron" json:"Alarm_poweron"`
	AlarmPoweroff           *time.Time `gorm:"column:Alarm_poweroff" json:"Alarm_poweroff"`
	AlarmCommentstate       *string    `gorm:"column:Alarm_commentstate" json:"Alarm_commentstate"`
	AlarmHistory            *string    `gorm:"column:Alarm_history" json:"Alarm_history"`
	CBID                    *string    `gorm:"column:CBID" json:"CBID"`
	AlarmRSSI1              *string    `gorm:"column:AlarmRSSI1" json:"AlarmRSSI1"`
	AlarmRSSI2              *string    `gorm:"column:AlarmRSSI2" json:"AlarmRSSI2"`
	NBRSSI                  *string    `gorm:"column:NBRSSI" json:"NBRSSI"`
	NBtime                  *time.Time `gorm:"column:NBtime" json:"NBtime"`
	Huhao                   *string    `gorm:"column:huhao" json:"huhao"`
	AlarmPictureCheck       *string    `gorm:"column:AlarmPictureCheck" json:"AlarmPictureCheck"`
	AlarmPictureCheckTime   *time.Time `gorm:"column:AlarmPictureCheckTime" json:"AlarmPictureCheckTime"`
	AlarmContractNo         *string    `gorm:"column:AlarmContractNo" json:"AlarmContractNo"`
	AlarmContractNoTime     *time.Time `gorm:"column:AlarmContractNoTime" json:"AlarmContractNoTime"`
	AlarmDeliveryNoteNo     *string    `gorm:"column:AlarmDeliveryNoteNo" json:"AlarmDeliveryNoteNo"`
	AlarmDeliveryNoteNoTime *time.Time `gorm:"column:AlarmDeliveryNoteNoTime" json:"AlarmDeliveryNoteNoTime"`
	WXAccountName           *string    `gorm:"column:WXAccountName" json:"WXAccountName"`
	WXAccountPassword       *string    `gorm:"column:WXAccountPassword" json:"WXAccountPassword"`
	WXRestMomey             *string    `gorm:"column:WXRestMomey" json:"WXRestMomey"`
}

// TableName SysCustomer's table name
func (*SysCustomer) TableName() string {
	return TableNameSysCustomer
}
